version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install pandas numpy scikit-learn joblib feature-engine boto3 requests pyarrow xgboost
  build:
    commands:
      - python training/build_training_data.py
      - python training/train_model.py
  post_build:
    commands:
      - echo "Done"